#!/bin/bash

echo '[:] checking dependencies'

type redis-cli >/dev/null 2>&1 || { echo >&2 "redis-server not installed. Exiting."; exit 1; }
type node >/dev/null 2>&1 || { echo >&2 "Node not installed. Exiting."; exit 1; }
type npm >/dev/null 2>&1 || { echo >&2 "npm not installed. Exiting. "; exit 1; }
type npm >/dev/null 2>&1 || { echo >&2 "groovy not installed. Exiting. "; exit 1; }

echo '[:] installing aberowl'

echo '[:] Downloading submodules'
git clone https://github.com/bio-ontology-research-group/AberOWL.git aberowl-server
git clone https://github.com/bio-ontology-research-group/aberowl-orepo.git aberowl-web
git clone https://github.com/bio-ontology-research-group/aberowl-sync aberowl-sync

cd aberowl-server
git submodule init
git submodule update

cd ../aberowl-sync
git submodule init
git submodule update

cd ../

echo '[:] Installing web dependencies'

cd aberowl-web
npm install

cd ../

echo '[:] Linking ontologies folders'
ln -s ../aberowl-server/onts/ aberowl-web/public/onts
ln -s ../aberowl-server/onts/ aberowl-sync/onts
ln -s ../../aberowl-server/onts/ aberowl-sync/db/onts

echo '[:] Done'

echo 'That is about it for the automagic side for now. Check the readme for other stuff.'
