- project:
    name: AberOWL

- job:
    name: SCHEMA
    project-type: pipeline
    concurrent: true
    dsl: |
      node {
        stage('Build') {
          sh '/usr/local/bin/groovy /home/hohndor/aberowl-meta/jenkins/workspace/CheckUpdate SCHEMA'
        }
        stage('Reason') {
          sh '/usr/local/bin/groovy /home/hohndor/aberowl-meta/jenkins/workspace/Classify SCHEMA'
        }
        stage('Index') {
          sh 'cd /home/hohndor/aberowl-meta/jenkins/workspace/ && /usr/local/bin/groovy /home/hohndor/aberowl-meta/jenkins/workspace/Index SCHEMA'
        }
        stage('Finalize') {
          sh '/usr/local/bin/groovy /home/hohndor/aberowl-meta/jenkins/workspace/Restart SCHEMA'
        }
      }
    sandbox: true
    triggers:
      - timed: '@daily'
